spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 432402456390-5cf5oa353ii1df091bs2u72jbmuq8c9q.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://todoc.site/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: email, profile

          kakao:
            client-id: 227996f677aa49a8999cd1218f0dc21a
            client-secret: fWlK1ri8Yc3XvmfaOPBIYL7D4WB2Mnwl
            redirect-uri: https://todoc.site/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

          naver:
            client-id: NUo9moYA0WeT6_Hl1efX
            client-secret: cw9aY6P1fq
            redirect-uri: https://todoc.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email, name
            client-name: Naver

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response