spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: a1a2a4a562@gmail.com
    password: majd gzbo ebvo ubmp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000